### ISSUE TITLE
Add Phylotrees as smart component

### ISSUE THREAD

**Issue by ctcncgr** [legumeinfo/web-components#10]
I need to refactor the existing code to add the phylotrees as a smart component.

**Comment by ctcncgr** [comment]
OK. I have a component staged for drawing the trees but am really struggling to get tnt to import into TS correctly.

Thoughts on whether or not we continue to use tnt? Do we want to try another tree library?

I might just be missing something simple about TS. 

I was considering swapping to:

https://gitlab.com/cgps/phylocanvas/phylocanvas.gl

but I'm not sure this is a good choice.

I run into similar import problems with this when I TSC:

```
import PhylocanvasGL, { TreeTypes } from "@phylocanvas/phylocanvas.gl";
```

Here is the Error:

```
[legumista@ctc-apollo web-components]$ npm run build

> legumeinfo/web-components@0.0.1 build
> tsc

src/lis-phylotree.ts:3:42 - error TS7016: Could not find a declaration file for module '@phylocanvas/phylocanvas.gl'. '/var/www/html/simple_query/web-components/node_modules/@phylocanvas/phylocanvas.gl/dist/phylocanvas.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/phylocanvas__phylocanvas.gl` if it exists or add a new declaration (.d.ts) file containing `declare module '@phylocanvas/phylocanvas.gl';`

3 import PhylocanvasGL, { TreeTypes } from "@phylocanvas/phylocanvas.gl";
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in src/lis-phylotree.ts
```

There is no types library for this or TnT.

Thoughts?

**Comment by alancleary** [comment]
I definitely owe @ctcncgr an apology for suggesting he bundle these outdated libraries in the first place. What a waste of time that was!

The new solution - specifying libraries like TnT as external dependencies - will not only keep our bundle small, but also prevent API users from loading JS files that they don't actually need if they're not using a component that depends on them. For example:
```html
<!-- the LIS web component library -->
<script src="lis-web-components.js"></script>

<!-- the external dependency you need to add for certain Web Components -->
<script src="tnt.js"></script>

<!-- a Web Component that uses the external dependency -->
<connors-phylo-tree-element></connors-phylo-tree-element>
```

**Comment by alancleary** [comment]
Superseded by issue #144. Closing but please keep the component/lis-phylotree branch intact for reference.
