### ISSUE TITLE
Add search component example for trait search in LIS-PB

### ISSUE THREAD

**Issue by ctcncgr** [legumeinfo/web-components#11]
Sven and I will extend the graphql backend to handle trait requests. We will then extend the existing search component or will build a new smart component for displaying the trait data.

the server repo that I have been using is here:

https://github.com/legumeinfo/graphql-server

**Comment by ctcncgr** [comment]
Sven has the server running on the peanut base VM and is working on a trait query now. We might want a bit of help with an example (or at least I wasn't very helpful for one) of the type of query we are envisioning against minimine.

@svengato may have already solved this, if not @adf-ncgr may be the best to supply an example query.

**Comment by svengato** [comment]
MiniMine does not contain any Traits, but ArachisMine does. As a test, I
wrote a query in R that gives ArachisMine a keyword and returns each
matching Trait's name and description.

**Comment by sammyjava** [comment]
And y'all let me know when you want more types of data in MiniMine, easy to do. Right now it has what LegumeMine has.

**Comment by svengato** [comment]
I would like to get some Traits into MiniMine, as ArachisMine supposedly has them but is not giving me results for either the gene keyword search or trait keyword search in this web-components demo.

**Comment by svengato** [comment]
I just realized this may be an HTTP v. HTTPS issue (as Connor said yesterday, "You may not be able to use the web interface unless the server is hosted on https."). I was running both the modified graphql-server and web-components locally on wolfburn (not dev-pb-jekyll yet), and the gene and trait keyword search queries to ArachisMine do not work through the web-components example application, but do work as expected through curl. That is reassuring, so I will pick it up again tomorrow.

**Comment by sammyjava** [comment]
Well I'm happy to add a GWAS or two to MiniMine in any case.

**Comment by svengato** [comment]
Added the trait keyword search web component in this repository, plus a keyword search page that uses it in [PeanutBase/jekyll-peanutbase](https://github.com/PeanutBase/jekyll-peanutbase), and the related trait API in [legumeinfo/graphql-server](https://github.com/legumeinfo/graphql-server).

These provide the basic functionality, we can open new issues for future enhancements.
