### ISSUE TITLE
Unknown (supercontig):start-stop is not a genomic region specification

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/web-components#118]
for example:
location: [aesev.CIAT22838.gnm1.Unknown (supercontig):2375348-2388727 (-1)](https://jekyll-dev.lis.ncgr.org/tools/search/gene-search.html?page=1&genus=Aeschynomene&species=evenia&strain=CIAT22838&identifier=&description=IPR000767&geneFamilyIdentifier=#modal)
NB: this probably is not with the dumb old web component per se but either with the graphql code or the shim. Feel free to move it to a more appropriate repo! 
Linkouts would be able to handle this appropriately if the supercontig id were actually given, otherwise not.

**Comment by alancleary** [comment]
"aesev.CIAT22838.gnm1.Unknown" is the identifier that's received from Intermine. This can be confirmed by inspecting the link in question and looking at the "data-location" attribute, which contains the identifier verbatim as it came from Intermine.

**Comment by adf-ncgr** [comment]
Yeah, I think the issue is that Intermine treats supercontigs as a different class than chromosomes, but I think there needs to be someplace where the genomic location is formed from a non-chromosomal position if it doesn't have one.

**Comment by adf-ncgr** [comment]
Actually, this one works as desired:
location: [vigra.VC1973A.gnm6.scaffold_7 (supercontig):698657-700123 (1)](https://jekyll-dev.lis.ncgr.org/tools/search/gene-search.html?page=1&genus=Vigna&species=radiata&strain=&identifier=&description=&geneFamilyIdentifier=#modal)
so I'm not sure why the example I gave above is behaving differently. Will investigate further as time allows.

**Comment by sammyjava** [comment]
The (supercontig) is being inserted in web-components: graphql-server is returning the correct location, without the (supercontig) addition, and the linkout service URLs don't have the (supercontig) in them. I'll track it down.
```json
{
  "data": {
    "gene": {
      "identifier": "vigra.VC1973A.gnm6.ann1.Vradi0007s00010",
      "locations": [
        {
          "supercontig": {
            "identifier": "vigra.VC1973A.gnm6.scaffold_7"
          },
          "start": 698657,
          "end": 700123,
          "linkouts": [
            {
              "href": "https://gcv.legumeinfo.org/tools/gcv/search?q=vigra.VC1973A.gnm6.scaffold_7:698657-700123&sources=lis",
              "text": "View vigra.VC1973A.gnm6.scaffold_7:698657-700123 in Genome Context Viewer"
            },
            {
              "href": "https://vigna.legumeinfo.org/tools/jbrowse2?session=spec-%7B%22views%22%3A%5B%7B%22assembly%22%3A%22vigra.VC1973A.gnm6%22%2C%22loc%22%3A%22vigra.VC1973A.gnm6.scaffold_7%3A698657-700123%22%2C%22type%22%3A%20%22LGV%22%2C%22tracks%22%3A%5B%22vigra.VC1973A.gnm6.ann1%22%5D%7D%5D%7D",
              "text": "View vigra.VC1973A.gnm6.scaffold_7:698657-700123 in JBrowse2"
            }
          ]
        }
      ]
    }
  }
}
```

**Comment by sammyjava** [comment]
And if there's any confusion, `Unknown` is an actual aesev supercontig, and is correctly given by graphql:
```json
{
  "data": {
    "gene": {
      "identifier": "aesev.CIAT22838.gnm1.ann1.Ae0001050",
      "locations": [
        {
          "supercontig": {
            "identifier": "aesev.CIAT22838.gnm1.Unknown"
          },
          "start": 2375348,
          "end": 2388727,
          "linkouts": [
            {
              "href": "https://gcv.legumeinfo.org/tools/gcv/search?q=aesev.CIAT22838.gnm1.Unknown:2375348-2388727&sources=lis",
              "text": "View aesev.CIAT22838.gnm1.Unknown:2375348-2388727 in Genome Context Viewer"
            },
            {
              "href": "https://aeschynomene.legumeinfo.org/tools/jbrowse2?session=spec-%7B%22views%22%3A%5B%7B%22assembly%22%3A%22aesev.CIAT22838.gnm1%22%2C%22loc%22%3A%22aesev.CIAT22838.gnm1.Unknown%3A2375348-2388727%22%2C%22type%22%3A%20%22LGV%22%2C%22tracks%22%3A%5B%22aesev.CIAT22838.gnm1.ann1%22%5D%7D%5D%7D",
              "text": "View aesev.CIAT22838.gnm1.Unknown:2375348-2388727 in JBrowse2"
            }
          ]
        }
      ]
    }
  }
}
```

**Comment by adf-ncgr** [comment]
Thanks, I just also realized that "Unknown" here is what they used instead of calling it "chromosome0" or similar. So this is a non-issue, I don't think there's anything else to track down, just me getting confused- closing.

**Comment by sammyjava** [comment]
Not so fast. We appended (chromosome) and (supercontig) at some point to indicate what the sequence is, but it shouldn't be shown like that, it's NOT what the location actually is and creates an incorrect location on a cut and paste operation by the user. I'll move those out of the way. I realize it's cosmetic, but it's wrong cosmetics.

**Comment by sammyjava** [comment]
Done, in adbae22 it's now after the strand indication.

[aesev.CIAT22838.gnm1.Unknown:2375348-2388727 (-1) (supercontig)](http://192.168.0.113:8000/dev/examples/lis-gene-search-with-linkouts.html?page=1&genus=&species=&strain=&identifier=aesev.CIAT22838.gnm1.ann1.Ae0001050&description=&geneFamilyIdentifier=#modal)

**Comment by sammyjava** [comment]
(FYI fixed URL, I had copied from my local dev.)
