### ISSUE TITLE
Move component specs to /specs here; add linkouts UI spec

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/web-components#124]
Reminder to me to move the specs that are over on **component-search-ui-src** to here so we have component specifications and code in the same place.

Then add the linkouts UI spec that didn't get written because there wasn't an obvious place to put it. :)

**Comment by alancleary** [comment]
@sammyjava I actually just sent you an email about this. I would've responded here if I had noticed in time! The short of it is I think we should consider what to do about technical specs at a project level since some specs may span multiple repos.

**Comment by sammyjava** [comment]
Yup, no problem. I just wanted something in place before we set the kiddies on it. We'll stick with the current repo that Steven set up and modify later. I'll wipe this branch for now, no biggy.

**Comment by alancleary** [comment]
> Yup, no problem. I just wanted something in place before we set the kiddies on it. We'll stick with the current repo that Steven set up and modify later. I'll wipe this branch for now, no biggy.

I think having something in place is a good idea. Maybe just rename the component-search-ui-srs repo to something more generic?

**Comment by sammyjava** [comment]
Done. It's now website-ui-specs. I updated the PDF (although I plan to screen share it anyway).
