### ISSUE TITLE
Separate READMEs for GitHub and NPM

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/web-components#158]
PR #157 adds a GitHub workflow that builds and publishes the web components package and publishes it to NPM when a release is tagged. However, the readme that's shown on NPM is the same as on GitHub. This readme was originally made for  GitHub and is full of instructions for developers and has no instructions for users. Since NPM is intended for users, we should add a second readme for NPM.

[This StackOverflow answer](https://stackoverflow.com/a/65676410) suggests that this is as simple as moving the current readme into the `.github/` directory and putting a new readme with user instructions in its place. Conveniently, GitHub will use the readme in the `.github/` directory and and NPM will use the readme in the root of the repository.

**Comment by sammyjava** [comment]
Cool solution.

**Comment by alancleary** [comment]
Done in PR #164
