### ISSUE TITLE
Version 1.1.0 release

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/web-components#218]
The updated gene search component that supports limiting the genus to a predefined value has been merged into main, and the trait search component will be merged soon. This probably justifies making a minor version release of the library. Other than updating dependencies, is there anything else people can think of that should be included in the next release?

**Edit:** Here's the release checklist.
- [x] Create a branch for the release. **Branch `release-v1.1.0`**
- [x] Update the dependencies. The dependabot PR backlog is not comprehensive and doesn't include transitive dependencies, and merging them one at a time tends to break things, so the best way to do this is manually with npm. **Done in #253**
- [x] Bump the `"version"` number in `package.json` and reinstall the dependencies so the correct version number is in `package.lock.json`. **Done in commit 169a996916cbbe05464b5e748d61543a2cbf0cca**
- [x] Open a PR that merges the release branch into main. **Done in #254**
- [x] Merge the release PR after it passes testing and review.
- [x] Tag a corresponding release on GitHub. This will trigger an automated NPM package build on GitHub. If the package build succeeds it will be automatically published to NPM.

**Comment by sammyjava** [comment]
Not I.

**Comment by svengato** [comment]
no

**Comment by adf-ncgr** [comment]
release minor and often seems like a good approach (not that we're in much danger of the latter anytime soon)

**Comment by StevenCannon-USDA** [comment]
If the question is "should be included in the **next** release?", is this a request for input about new features?

If so, then I'd like to revisit the tabular layout. I don't object to tabular layout per se, but column widths and numbers are such that I can't see the rightmost several columns without stretching my browser (Chrome or Safari) well beyond the width of my laptop screen. That's going to be irritating for users. What are the options for setting column widths? Addition of a horizontal scroll bar for the results would also be good I think.

**Comment by That-Thing** [comment]
Does the scrollbar not appear at the very bottom of the results?
Browsers should handle overflow automatically.

**Comment by StevenCannon-USDA** [comment]
Horizontal scroll: not for me. It's possible that it is a Mac thing - maybe configurable, but I haven't figured out how.
https://discussions.apple.com/thread/253224482
https://apple.stackexchange.com/questions/420108/no-horizontal-scroll-in-safari-bug-or-pref

**Comment by alancleary** [comment]
> release minor and often seems like a good approach (not that we're in much danger of the latter anytime soon)

For sure. I just  don't want to push a new release and then be asked to push another immediately after because I overlooked a feature!

>If the question is "should be included in the next release?", is this a request for input about new features?
>
>If so, then I'd like to revisit the tabular layout. I don't object to tabular layout per se, but column widths and numbers are such that I can't see the rightmost several columns without stretching my browser (Chrome or Safari) well beyond the width of my laptop screen. That's going to be irritating for users. What are the options for setting column widths? Addition of a horizontal scroll bar for the results would also be good I think.

Every paginated search element has a [`tableColumnClasses` property](https://legumeinfo.github.io/web-components/classes/mixins.LisPaginatedSearchElementInterface.html#tableColumnClasses) you can use to set the classes on specific columns  at run-time. This is primarily intended for controlling column widths via [UIkit classes](https://getuikit.com/docs/table#column-width-modifier).

Regarding horizontal scroll: @That-Thing is correct; there's already horizontal scrolling. Here's the response I was typing when he responded: Every paginated search should already be endowed with this functionality [via the mixin](https://github.com/legumeinfo/web-components/blob/main/src/mixins/lis-paginated-search-mixin.ts#L689). Specifically, the result table's container will use as much horizontal space as possible. If the table is still wider than the container then a horizontal scrollbar should automatically appear. If this is not happening then the element the web component is inside of is not properly restricting the width of the component. What may be happening, though, is that the scrollbar appears at the bottom of the result container, meaning you don't see it until you scroll past all the results. It's not ideal but I figured we could deal with it when the time comes, which may be now...

**Comment by StevenCannon-USDA** [comment]
Thanks for the responses, @alancleary and @That-Thing.
It sounds like the layout/scroll topic maybe deserves its own issue. But to prime that issue, here's what I am seeing. This is s shot from Safari, but Chrome and Firefox look the same on my system (MacOS 13.5.2). This screenshot runs to the bottom of the browser window.
<img width="1269" alt="Screenshot 2023-10-05 at 11 32 36 AM" src="https://github.com/legumeinfo/web-components/assets/3588740/28c8f64b-9be4-4a8f-ae2b-6dec5be3407a">

**Comment by sammyjava** [comment]
*cough* table layout *cough cough*

**Comment by alancleary** [comment]
@StevenCannon-USDA The horizontal scrollbar doesn't appear in my browser until I mouse over the table. Can you conform whether or not that's happening on your end?

**Comment by StevenCannon-USDA** [comment]
@alancleary - Confirming: I don't get a horizontal scrollbar on table mouseover - in Safari, Chrome, or Firefox. 

I'll mention that the screenshot I attached previously was a bad example! For that result, everything fit in the screen. A search of `13G357700` in the name field (sans Glyma) gives a wider output that loses GENUS, SPECIES, STRAIN

**Comment by adf-ncgr** [comment]
I see the same behavior as @StevenCannon-USDA, either on Mac or PC (both tests in Chrome). Not sure if this is a regression, seems like something we would have noticed but maybe not.

**Comment by alancleary** [comment]
I realize now that you're using the the web component on legumeinfo; I was using the dev example in the web-components repo. The horizontal scrolling on the legumeinfo gene search page appears to be broken. This is because, as I previously described, the component's container is not properly restricting its width when it hits the edge of the page.

The the main container in the base layout of the theme that wraps all page content seems to be at fault, specifically the `uk-flex` class seems to be the cause of the breakage. Looking at the commit log, it appears this class was added so that the card column is shown to the right of the main content instead of being pushed below it. I'll open a new issue for this and make fixing it a priority.

**Comment by maxglycine** [comment]
I am not sure how to visualize this.  What is the secret? Setting up a code space and issuing "make" was not the way.

**Comment by alancleary** [comment]
> release minor and often seems like a good approach (not that we're in much danger of the latter anytime soon)

So this issue has languished. I'm going to go ahead and follow @adf-ncgr's "release minor and often" adage and make a release. Standby!

**Comment by alancleary** [comment]
v1.1.0 has been released. If anyone wants to continue a conversation that was happening here please open a new issue for that specific conversation. Closing.
