### ISSUE TITLE
web-component(s) for linkouts

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/web-components#31]
Now that we have linkout service(s) implemented, we should have a standard way of injecting them into the site. At this point, we only have GET-based methods returned from the linkout service but will need to think about how to handle POST-based methods too (e.g. in the case where we want to POST a set of gene ids to intermine list creation or a set of regions to its region-based form). In addition to the dumb component, we should have some good examples of how to interact with the linkout service and instantiate the component with its results.

**Comment by adf-ncgr** [comment]
note that the possible plurality of components here relates to the fact that there are a few linkout service endpoints for different types of ids- but given that they are likely going to return the same structure, and the component itself is dumb, perhaps there's no need for more than one.

**Comment by alancleary** [comment]
> note that the possible plurality of components here relates to the fact that there are a few linkout service endpoints for different types of ids- but given that they are likely going to return the same structure, and the component itself is dumb, perhaps there's no need for more than one.

I suggest starting with a single implementation and abstracting as needed, similar to what we've done with the search components, i.e. we started with a single gene search component and ended up with a paginated search mixin.

> Now that we have linkout service(s) implemented, we should have a standard way of injecting them into the site. At this point, we only have GET-based methods returned from the linkout service but will need to think about how to handle POST-based methods too (e.g. in the case where we want to POST a set of gene ids to intermine list creation or a set of regions to its region-based form). In addition to the dumb component, we should have some good examples of how to interact with the linkout service and instantiate the component with its results.

FYI the [fetch API](https://developer.mozilla.org/en-US/docs/Web/API/fetch) used in the examples in the `dev/` directory supports POST requests.
