### ISSUE TITLE
Change Publication ID example at SoyBase Trait Association Search

### ISSUE THREAD

**Issue by StevenCannon-USDA** [legumeinfo/web-components#327]
I would like the example for the Publication ID at the Jekyll-SoyBase Trait Association Search to be changed to

10.3389/fpls.2019.00401

The current example (10.1371/journal.pone.0054985) fails (my error).

**Comment by That-Thing** [comment]
Updated and created [PR](https://github.com/soybase/jekyll-soybase/pull/86) in jekyll-soybase repo.

**Comment by alancleary** [comment]
> Updated and created [PR](https://github.com/soybase/jekyll-soybase/pull/86) in jekyll-soybase repo.

Bearing the fruits of your labor. Thanks @That-Thing.
