### ISSUE TITLE
Add more examples

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/web-components#33]
Specifically, every element should have an example in the `dev/` directory. Be sure to add a link to each example in the `index.html` file at the root of the repo.

**Comment by ctcncgr** [comment]
I have added the phylotree component in the component/lis-phylotree branch. I need to finish the documentation for it. I will add the gene search with multiple attributes next.

**Comment by alancleary** [comment]
Closing this issue since I'm wrapping up the documentation epic.
