### ISSUE TITLE
Release 1.4.0

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/web-components#336]
- [x] Create a branch for the release.
- [x] Update the dependencies. The dependabot PR backlog is not comprehensive and doesn't include transitive dependencies, and merging them one at a time tends to break things, so the best way to do this is manually with `npm`.
- [x] Do a test build of the NPM package on your local machine so you know if something is going off the rails before the automated build action on GitHub.
- [x] Bump the `"version"` number in `package.json` and reinstall the dependencies so the correct version number is in `package-lock.json`.
- [x] Open a PR that merges the release branch into main.
- [x] Merge the release PR after it passes testing and review.
- [x] Tag a corresponding release on GitHub. This will trigger an automated NPM package build on GitHub. If the package build succeeds it will be automatically published to NPM.

**Comment by adf-ncgr** [comment]
@alancleary can you verify if this is expected or I am doing something wrong? 
```
npm test

> @legumeinfo/web-components@1.3.0 test
> npm run test:dev && npm run test:prod


> @legumeinfo/web-components@1.3.0 test:dev
> wtr

Error: Could not find any test files with pattern(s): ./test/**/*_test.js
```
This is prior to doing any dependency updating, so either I've done something dumb in my setup or this testing stuff is still aspirational...

**Comment by alancleary** [comment]
@adf-ncgr The testing scripts in `package.json` were brought over from the starter repo we used to bootstrap this repo. No tests have actually been implemented. Hopefully this will be changing in the nearish future.

**Comment by adf-ncgr** [comment]
OK, so I will read that as "aspirational"; serves me right for reading (and believing) the README. Thanks!

**Comment by alancleary** [comment]
The README was also brought over from the starter repo :sweat_smile:

**Comment by adf-ncgr** [comment]
@alancleary, more surrogate release management help needed. Since one of the dependencies to be bumped is lit-analyzer, I thought I should try `npm run lint:lit-analyzer` but this resulted in `✖ 25 problems in 10 files (13 errors, 12 warnings)`. The same result is given on a fresh clone of the repo (ie with the current set of dependency versions), so not sure if it is actually something that needs fixing? Please advise when you get a chance (but beware that the errors seem unlikely to be things that I'll be competent to fix)

**Comment by alancleary** [comment]
Yet another carryover from the starter repo. We stopped using it around the time we introduced es-lint and prettier with the plan to get it working again at some point. Perhaps @ctcncgr remembers why we did this. Regardless, don't worry about it. Thanks for checking!

**Comment by adf-ncgr** [comment]
final box checked. release v1.4.0 is live
