### ISSUE TITLE
Pangene lookup component's download button resets pangination

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/web-components#400]
If you do a lookup in the pangene lookup component, click the next page button, and then click the download button, the pagination will get reset to page 1 but the results in the table will not change. This should be fixed one way or another, e.g. by not changing the pagination value or clearing the results in the table.

**Comment by adf-ncgr** [comment]
I vote for not changing pagination value (why would clicking Download do anything but download?)

**Comment by adf-ncgr** [comment]
PS. I just saw the probably unintentional joke in the issue title: "pangination"

**Comment by alancleary** [comment]
Fixed in PR #404
