### ISSUE TITLE
Modal Core Component

### ISSUE THREAD

**Issue by ctcncgr** [legumeinfo/web-components#43]
Add a core component for a modal. Takes a string to be rendered as a paragraph in `modalString` or takes a list of strings to be rendered as rows in a headerless table from `modalList` for blocking ease.

**Comment by alancleary** [comment]
Core components should each have a singular purpose, so a modal component should be concerned with just making a modal, but not the content of the modal. The modal can be used by a higher level component for a specific type of content, but I think having the modal component take a list of objects to create `<a>` and `<p>` tags is too specific for a core component.

**Comment by ctcncgr** [comment]
Np. The modal can just accept something to render in data. If that something is a list I will render each item as a row.

**Comment by ctcncgr** [comment]
After thinking about this again a second ago. The component will have `header` and `content` attributes. The header will be populated with the string provided in `this.header` and the modal body will be populated with `this.content`. This lets formatting be on the provider of the content not the component itself.

**Comment by alancleary** [comment]
Why can't the content just be provided by a slot? Then you could put another component as the content:
```html
<lis-modal>
    <another-component></another-component>
</lis-model>
```

**Comment by ctcncgr** [comment]
Gotcha, I thought about doing this, but thought maybe it was too generic. I'm thinking about keeping the `header` attribute. The uk-modal has its own header tag that looks pretty good, `<div class="uk-modal-header"></div>`. If header is not supplied it doesn't render.

**Comment by ctcncgr** [comment]
I'm going to remove header in favor of named slots. `<slot name="header"><h1>Modal Header</h1></slot>`

**Comment by alancleary** [comment]
I think either solution (named slot or component property/attribute) is good. It'll be nice to have a component that makes modals consistent across the site!

**Comment by ctcncgr** [comment]
Ok this has been a very good learning experience here. The shadow DOM enables the use of slots. We disable the shadow DOM to prevent component encapsulation and allow the style to be inherited from the page, therefore slots don't work properly.

@alancleary had suggested a work around like the following, "You might be able to get around it by wrapping the template html in a named slot and then nesting the unnamed (i.e. default) slot inside of it.", I will be trying this first, then will punt and use attributes.

Is the shadow DOM required for web components? Definitely not, and interestingly if you don't really want encapsulation you really don't want to use it. Good stuff.

https://www.hjorthhansen.dev/you-might-not-need-shadow-dom/

**Comment by ctcncgr** [comment]
After trying pretty hard to make slots work correctly without the shadow DOM I have decided that it is not worth doing (although definitely is very good to know about). To maintain style for our sites within the components we disable the shadow DOM. It is important when designing these components to keep this in mind. Docs and PR inc.

**Comment by ctcncgr** [comment]
Closing, PR #44 accepted.
