### ISSUE TITLE
Slot Controller

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/web-components#45]
In PR #44 we came up with [a solution](https://github.com/legumeinfo/web-components/pull/44#discussion_r1124892042) that allows our components to be used as if they have slots, even though they disable the Shadow DOM. We discussed encapsulating this in a controller so that named slots could be easily supported as well and so each component that wants to use (named) slots doesn't have to reimplement the solution. That is the purpose of this issue - implement a controller that allows components that have their Shadow DOM disabled to use slots. Once implemented, the solution can be used to solve issue #38.

**Comment by alancleary** [comment]
@ctcncgr Do you want to implement this? I think it sounds fun so I don't mind doing it if you don't want to .

**Comment by ctcncgr** [comment]
@alancleary I have to work on some other stuff this week so likely won't get to it for a week or so if you want to start it. I can hop in when you want/need additional help and input.

**Comment by alancleary** [comment]
> I have to work on some other stuff this week so likely won't get to it for a week or so if you want to start it. I can hop in when you want/need additional help and input.

Ditto. I'll leave it unassigned for now and whoever finds time first can have at it!

**Comment by alancleary** [comment]
Done in PR #49. Closing.
