### ISSUE TITLE
Should lis-paginated-search-mixin.ts be used without a form?

### ISSUE THREAD

**Issue by ctcncgr** [legumeinfo/web-components#46]
Should (can?) `https://github.com/legumeinfo/web-components/blob/main/src/mixins/lis-paginated-search-mixin.ts` be used without a `<form>` tag? 

If so, should we change the protected function `renderForm()` to something like `renderContent()`?

**Comment by alancleary** [comment]
Can you give more details about your use case? Depending on what you're trying to achieve it might make sense to not use the mixin or make a new mixin.

**Comment by ctcncgr** [comment]
Andrew's linkout microservice is wrapped in a js function that retrieves data and returns it formatted in a very similar way to the existing gene search. There are two attributes, one is a `name` that is converted into a hyperlink using the `url` attribute from the microservice and the other is a `description` returned directly from the microservice. This is fed an instance of `<lis-simple-table-element>` which is slotted in an `<lis-modal-element>`.

**Comment by alancleary** [comment]
The use case still isn't too clear to me. If you want to get rid of the form that initiates a search then how is a search going to be performed from the web component's perspective? Also, is Andrew's linkout service paginated? And how are you imagining the linkout web component will be used? I know you intend to put it in a modal; will a new modal and linkout component be created every time a link that activates the modal is clicked or will you just hard-code them in the page and reuse them?

In general I don't think using the paginated search mixin without an actual form element is going to be easy. The mixin is tightly coupled with the form so bypassing it altogether would require a pretty hacky solution. Probably the easiest way to get this to work would be to actually use a form but make it hidden and submit it programmatically. This wouldn't required any modifications to the mixin or hacks in the implementing class. However, implementing and managing a hidden form is still a level of misdirection.

So unless the linkout use case is basically identical to the paginated search except without the form, I think it's probably just worth implementing the functionality via a new component. Reimplementing features from the paginated search is a good idea, though. Having all the elements automatically update when a search is performed and completed is definitely worth encapsulating in a component.

**Comment by ctcncgr** [comment]
I think that really the mixin shouldn't be used without a form after fully digesting your response and learning a bit more about this. Closing
