### ISSUE TITLE
Should we prune some of our merged branches?

### ISSUE THREAD

**Issue by ctcncgr** [legumeinfo/web-components#47]
@alancleary @adf-ncgr should we remove some of our merged branches? Am I over thinking this?

**Comment by sammyjava** [comment]
I just deleted one. :)

**Comment by alancleary** [comment]
Yes! I don't like to delete other people's branches after I merge their PRs. I also habitually forget to delete my own branches :sweat_smile:

**Comment by ctcncgr** [comment]
Removed `component/lis-modal-element` after merge of #44. The PR will let me restore it if for w/e reason we need it back.

**Comment by ctcncgr** [comment]
I think we succeed at this. Anyone feel free to reopen when necessary.
